version: 0.2

env:
  variables:
    GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y openssh-client jq
      - mkdir -p ~/.ssh/ && chmod 700 ~/.ssh/
      - aws ssm get-parameter --name /codebuild/github/web/key.pem | jq -r .Parameter.Value > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  build:
    commands:
      - chmod +x aws/scripts/release.sh
      - aws/scripts/release.sh 'git@github.com:Starsona/web.git'
      - export RELEASE=`cat .release`
      - echo New hotfix branch $RELEASE
  post_build:
    commands:
    - echo Writing artifacts...
    - 'echo "{\"Parameters\": {\"GitBranch\":\"$RELEASE\"}}" > release.json'
artifacts:
  files:
  - release.json
  discard-paths: yes
