version: 0.2

env:
  variables:
    GIT_SSH_COMMAND: "ssh -i ~/.ssh/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

phases:
  install:
    commands:
      - apt-get update && apt-get install -y openssh-client jq
      - mkdir -p ~/.ssh/ && chmod 700 ~/.ssh/
      - aws ssm get-parameter --name /codebuild/github/web/key.pem | jq -r .Parameter.Value > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
  build:
    commands:
      - chmod +x aws/scripts/release.sh
      - echo Reading parameters from SSM...
      - aws ssm get-parameter --name ${PARAMETERS} | jq -r .Parameter.Value > parameters.json
      - cat parameters.json
      - export VERSION=`cat parameters.json | jq -r .Parameters.Version`
      - export GIT_BRANCH=`cat parameters.json | jq -r .Parameters.GitBranch`
      - export BASE_IMAGE_TAG=`cat parameters.json | jq -r .Parameters.BaseImageTag`
      - aws/scripts/release.sh 'git@github.com:Starsona/web.git'
      - export HOTFIX=`cat .hotfix`
      - echo New hotfix branch ${HOTFIX}
      - export CODEPIPELINE=`cat .codepipeline`
      - echo Codepipeline version ${CODEPIPELINE}
  post_build:
    commands:
    - echo Writing artifacts...
    - cat parameters.json | jq ".Parameters.Version = \"${CODEPIPELINE}\"" > codepipeline.json
    - aws ssm get-parameter --name /codepipeline/web/hotfix.json | jq -r .Parameter.Value | jq ".Parameters.Version = \"${HOTFIX}\" | .Parameters.GitBranch = \"${HOTFIX}\" | .Parameters.BaseImageTag = \"${BASE_IMAGE_TAG}\"" > hotfix.json
    - cat codepipeline.json hotfix.json
    - echo Updating SSM...
    - aws ssm put-parameter --name /codepipeline/web/codepipeline.json --type String --overwrite --value file://./codepipeline.json
    - aws ssm put-parameter --name /codepipeline/web/hotfix.json --type String --overwrite --value file://./hotfix.json
artifacts:
  files:
  - hotfix.json
  - codepipeline.json
  discard-paths: yes
