Description: Create a CodePipeline to include Nested CloudFormation, CodeBuild and Approval steps.
Parameters:

  MajorVersion:
    Type: Number
    Description: Major version
    Default: 1

  MinorVersion:
    Type: Number
    Description: Minor version, increment each time code merged to production
    Default: 0

  BaseImageTag:
    Type: String
    Description: Base image tag
    Default: ":20190216"

  GitBranch:
    Type: String
    Description: Git branch
    Default: 'ubuntu-18.04'

  GithubToken:
    Type: String
    Description: Github OAuth token
    Default: 51639390163a192eb23b6a74aefcfa8369b62518

Resources:
  BuildImages:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'images']]
      Description: Build images
      ServiceRole: arn:aws:iam::376169159073:role/service-role/codebuild-starsona-service-role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:17.09.0
        PrivilegedMode: true
        EnvironmentVariables:
          - { Name: BASE_IMAGE_TAG, Value: !Ref 'BaseImageTag' }
          - { Name: GIT_BRANCH, Value: !Ref 'GitBranch' }
          - { Name: MAJOR_VERSION, Value: !Ref 'MajorVersion' }
          - { Name: MINOR_VERSION, Value: !Ref 'MinorVersion' }

      Source:
        Type: CODEPIPELINE
        BuildSpec: aws/codebuild/buildspec-images.yml
      TimeoutInMinutes: 15

  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Ref AWS::StackName
      RoleArn: arn:aws:iam::376169159073:role/AWS-CodePipeline-Service
      Stages:
        -
          Name: Source
          Actions:
            -
              Name: github
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              OutputArtifacts:
                - Name: source
              Configuration:
                Owner: Starsona
                Repo: web
                PollForSourceChanges: false
                Branch: !Ref 'GitBranch'
                OAuthToken: !Ref 'GithubToken'
              RunOrder: 1
        -
          Name: Build
          Actions:
            -
              Name: images
              InputArtifacts:
                - Name: source
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: build
              Configuration:
                ProjectName: !Ref 'BuildImages'
              RunOrder: 1
        -
          Name: Staging
          Actions:
            -
              Name: app
              InputArtifacts:
                - Name: source
                - Name: build
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CREATE_UPDATE
                RoleArn: arn:aws:iam::376169159073:role/AWS-CodePipeline-Service
                Capabilities: CAPABILITY_IAM
                StackName: upgrade-web-app
                TemplateConfiguration: build::upgrade-web.json
                TemplatePath: source::aws/cloudformation/web.yml
              RunOrder: 1

      ArtifactStore:
        Type: S3
        Location: codepipeline-us-east-1-219080120354

